services:
  db:
    image: postgres:17
    container_name: currency-db
    environment:
      POSTGRES_DB: currencydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
